### ISSUE TITLE
Create Docker-Compose

### ISSUE THREAD

**Issue by DanielOber** [it-at-m/refarch-templates#10]
Create a new directory within the refarch-template repository named stack, and include a docker-compose.yml file inside it. This file should contain postgres, pgadmin, keycloak, keycloakmigration and API-Gateway. You can refer to the [digiwf ](https://github.com/it-at-m/digiwf-core/tree/dev/stack)project on GitHub for guidance on how to write the file and what else ist needed for the keycloackmigration.

The local profile must be reconfigured to use the running docker services.

**Comment by devtobi** [comment]
Should this really be at the top level of the repo? Or is it something that's specific to the backend?

**Comment by DanielOber** [comment]
i think it should be top level, because it could be needed by every service and not only by a specific specific. For example, if you add a s3 bucket (minio) then the EAI / Frontend need to access it.
