### ISSUE TITLE
Check functionality of AppSwitcher

### ISSUE THREAD

**Issue by devtobi** [it-at-m/refarch-templates#100]
**Is your feature request related to a problem? Please describe.**
Check if the AppSwitcher component works out the box and if not, fix it.

**Describe the solution you'd like**
AppSwitcher works by default.

**Describe alternatives you've considered**
Remove AppSwitcher

**Additional context**
---

**Comment by eidottermihi** [comment]
If think the problem is more deployment related, because ATM the frontend depends on the availability of an `appswitcher-server` (https://github.com/it-at-m/appswitcher-server) deployment

There are two ways how we could handle this:

1) include a local deployment of `appswitcher-server` in the "local stack" and configure frontend to use this instance by default or
2) move the usage of appswitcher behind a "feature toggle", off by default (can then be enabled when deployed inside LHM, where a central instance of `appswitcher-server` is provided)

I could contribute any of those 2 options, what do you think @devtobi ?

**Comment by devtobi** [comment]
> If think the problem is more deployment related, because ATM the frontend depends on the availability of an `appswitcher-server` (https://github.com/it-at-m/appswitcher-server) deployment
> 
> There are two ways how we could handle this:
> 
> 1. include a local deployment of `appswitcher-server` in the "local stack" and configure frontend to use this instance by default or
> 2. move the usage of appswitcher behind a "feature toggle", off by default (can then be enabled when deployed inside LHM, where a central instance of `appswitcher-server` is provided)
> 
> I could contribute any of those 2 options, what do you think @devtobi ?

I guess a combination of the both suggested ways would be the best. 
- For local use we could use the AppSwitcher to switch between different services like the local KeyCloak UI, API documentation UI (e.g. Swagger or HAL Browser), PGAdmin, and more. Could this be achieved using the app-switcher? This way developers have all available development tools (which are accessible via browser) right at hand and don't need to bookmark various URLs in their browsers.
- For production build I guess it would be better point the URL to the internal LHM service. (with a note that the default domain is only reachable internally). But people can switch to their own hosted appswitcher-server by adjusting the value.

This would mean we would again need different env file settings for Vite dev and production build right?

**Comment by eidottermihi** [comment]
> For local use we could use the AppSwitcher to switch between different services like the local KeyCloak UI, API documentation UI (e.g. Swagger or HAL Browser), PGAdmin, and more. Could this be achieved using the app-switcher? This way developers have all available development tools (which are accessible via browser) right at hand and don't need to bookmark various URLs in their browsers.

I think that could be done, as long as those local services run on predefined ports or hostnames (and are not random or generated during deploy)

> For production build I guess it would be better point the URL to the internal LHM service. (with a note that the default domain is only reachable internally). But people can switch to their own hosted appswitcher-server by adjusting the value.
>
>This would mean we would again need different env file settings for Vite dev and production build right?

Yes, either via env files during build time.

Or some kind of run time configuration like getting config values from the backend or gateway. The run time variant has been done in the archetype (via Actuator Endpoint, https://git.muenchen.de/ccse/refarch-archetype/refarch-archetype-apigateway/-/merge_requests/75/diffs#5c44876d44f5a591614cb5a6fd3ea6a96a9e4873_0_35 ).

But maybe this is stuff for another issue: do we need "run time" configuration for the frontend? In most of my applications there has been this need, and most often there has been some kind of endpoint in the backend that was used for this stuff (Actuator Info or custom Endpoints like `/config`)

**Comment by devtobi** [comment]
> > For local use we could use the AppSwitcher to switch between different services like the local KeyCloak UI, API documentation UI (e.g. Swagger or HAL Browser), PGAdmin, and more. Could this be achieved using the app-switcher? This way developers have all available development tools (which are accessible via browser) right at hand and don't need to bookmark various URLs in their browsers.
> 
> I think that could be done, as long as those local services run on predefined ports or hostnames (and are not random or generated during deploy)
> 
> > For production build I guess it would be better point the URL to the internal LHM service. (with a note that the default domain is only reachable internally). But people can switch to their own hosted appswitcher-server by adjusting the value.
> > This would mean we would again need different env file settings for Vite dev and production build right?
> 
> Yes, either via env files during build time.
> 
> Or some kind of run time configuration like getting config values from the backend or gateway. The run time variant has been done in the archetype (via Actuator Endpoint, https://git.muenchen.de/ccse/refarch-archetype/refarch-archetype-apigateway/-/merge_requests/75/diffs#5c44876d44f5a591614cb5a6fd3ea6a96a9e4873_0_35 ).
> 
> But maybe this is stuff for another issue: do we need "run time" configuration for the frontend? In most of my applications there has been this need, and most often there has been some kind of endpoint in the backend that was used for this stuff (Actuator Info or custom Endpoints like `/config`)

Sounds great. I would move the discussion for run time config in frontend to a later point in time. I guess for now, setting it in the build via env variables is totally fine. :) You can create an issue for run time configurations for sure. :)

If you want to contribute a PR, I would ask you to take a look at the current local `docker-compose.yml` in `stack`. There you can add the additional service as well as find the URLs for the exposed services to the hostmachine.

**Comment by devtobi** [comment]
@eidottermihi We can close this issue now, right? :)
