### ISSUE TITLE
Add issue-Templates

### ISSUE THREAD

**Issue by DanielOber** [it-at-m/refarch-templates#11]
- what templates do we need
- do we need to change existing templates

**Comment by devtobi** [comment]
We discussed this today.
We want to include at least issue templates for:
- Bugs (Type: Bug, Priority: High)
- Docs (Type: Documentation, Priority: Low)
- Feature Request (Type: Enhancement, Priority: Medium)
- Maintenance Request (Type: Maintenance: Priority: Medium)
- Question/Support (Type: Question, Priority: High)

@DanielOber Do you agree with this?

https://github.com/Josee9988/project-template/tree/master/.github/ISSUE_TEMPLATE has some really nice template defaults we can use.

**Comment by DanielOber** [comment]
Yes 👍

**Comment by devtobi** [comment]
There were some small "errors" in the template. Created a follow-up bug-issue under https://github.com/it-at-m/refarch-templates/issues/131
