### ISSUE TITLE
change from renovate.json to renovate.json5

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/refarch-templates#12]
**Is your feature request related to a problem? Please describe.**
When we ignore dependencies we want document the reason too. With `json5` comments are possible.

**Describe the solution you'd like**
rename the file

**Describe alternatives you've considered**

**Additional context**
- https://github.com/it-at-m/Wahllokalsystem/pull/362

**Comment by devtobi** [comment]
Will be further processed in https://github.com/it-at-m/refarch-templates/issues/113
