### ISSUE TITLE
Provide engine information in package.json files

### ISSUE THREAD

**Issue by devtobi** [it-at-m/refarch-templates#125]
**Is your feature request related to a problem? Please describe.**
Currently its not defined which Node versions are supported by the Node-based templates.

**Describe the solution you'd like**
Engine information e.g.
```
  "engines" : { 
    "npm" : ">=8.0.0 <9.0.0",
    "node" : ">=16.0.0 <17.0.0"
  }
```
should be included in the `package.json`.

Additionally a custom  to your `.npmrc` with `engine-strict=true` can be provided to fail building when installing with incompatible version.

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by devtobi** [comment]
Insights: 
- `refarch-frontend` requires Node 20 as minimum (because of itm-appswitcher-vue), however this might be a false negative because I got it to work with Node 18 as well.
- `refarch-webcomponent` worked with Node 18 as well.

Because we are going to align the two templates in terms of tooling more and more in the future, I would like to keep both Engine requirements for both templates the same. (so either Node 18 for both, or Node 20 for both)

@DanielOber What do you think about this? Do you think its fine if we require Node 20? Or should I talk with maintainer for `itm-appswitcher-vue` to decrease requirements to Node 18?
I think Node 18 would be better, because its a LTS release as well.

**Comment by DanielOber** [comment]
> I think Node 18 would be better, because its a LTS release as well.

Node 20 is also [LTS](https://nodejs.org/en/blog/release/v20.9.0) or am i missing something? I would prefer to only go up with the version, not down
