### ISSUE TITLE
Mehr Unterhosen [Feature Request] 

### ISSUE THREAD

**Issue by darenegade** [it-at-m/refarch-templates#136]
### Relevant template

None

### Problem description (optional)

Wir haben zu wenig Unterhosen

### Desired solution

Mehr Unterhosen

### Additional context (optional)

![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExYmhnZ2R5NmF1b3JmNGk0OXZxeG8wc214eTByZ3I1NThuc2htZTl3bSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l0HlC8X5PmAUv6RyM/giphy.gif)

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devtobi** [comment]
Welcome-Bot funktioniert, Testissue wird wieder geschlossen.
