### ISSUE TITLE
[Maintenance] Add basic CI/CD pipeline

### ISSUE THREAD

**Issue by devtobi** [it-at-m/refarch-templates#149]
### Problem description (optional)

Currently our templates are not being checked.
Especially for upcoming Renovate updates we need to make sure the code builds and works as intended.

### Desired solution

- Separate GitHub workflow files that are run for every PR update
- Linting, Testing and Building should all run in parallel (thats why separate workflow makes sense)
- "Intelligent" filters should check beforehand which templates where modified (see https://github.com/it-at-m/refarch-templates/blob/main/.github/workflows/codeql.yaml for an example) and only run Linting/Testing/Building where required.

### Considered alternatives (optional)

---

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devtobi** [comment]
Blocked for now until we have the new tooling for Linting and Formatting in place. Needed because we want to separate configuration changes from reformatting and code fixes.

**Comment by langehm** [comment]
I need this 👍

**Comment by eidottermihi** [comment]
@devtobi maybe we could split this issue (or add subtasks) and proceed with "Testing and Building" (leave out linting for a later date)? 

This would already add a benefit to get at least feedback for compilation and test execution issues.
