### ISSUE TITLE
[Maintenance] Update to Vue 3.4 and introduce defineModel

### ISSUE THREAD

**Issue by langehm** [it-at-m/refarch-templates#175]
### Problem description (optional)

Current vuejs version is 3.3.x which does not support `defineModel`. This syntactic sugar comes with vuejs version 3.4

### Desired solution

Update to vuejs 3.4.x and replace all instances of defining modelValue and coherent definitions of emits with the new syntactic sugar `defineModel`

### Additional context (optional)

[Link to Vue 3.4](https://blog.vuejs.org/posts/vue-3-4)

## Potential Actions Needed

To fully leverage new features in 3.4, it is recommended to also update the following dependencies when upgrading to 3.4:
- Volar / vue-tsc@^1.8.27 (required)
- @vitejs/plugin-vue@^5.0.0 (if using Vite)
- nuxt@^3.9.0 (if using Nuxt)
- vue-loader@^17.4.0 (if using webpack or vue-cli)

> If using TSX with Vue, check actions needed in [Removed: Global JSX Namespace](https://blog.vuejs.org/posts/vue-3-4#removed-global-jsx-namespace).

> Make sure you are no longer using any deprecated features (if you are, you should have warnings in the console telling you so). They may have been [removed in 3.4](https://blog.vuejs.org/posts/vue-3-4#other-removed-features).

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by langehm** [comment]
I can submit a PR myself 😉

**Comment by devtobi** [comment]
> I can submit a PR myself 😉

Sounds great. However keep in mind we will also need those changes for the upcoming webcomponent template that not available yet. However you can provide a PR for the frontend template and we will take your changes into account once the webcomponent template is available. :)

**Comment by devtobi** [comment]
Done with https://github.com/it-at-m/refarch-templates/pull/179. Issue can be closed. ;)
