### ISSUE TITLE
[Maintenance] struktur anpassen

### ISSUE THREAD

**Issue by hupling** [it-at-m/refarch-templates#186]
### Desired solution

- [ ] readme anpassen
- [ ] dockerfile auf oberste ebene löschen
- [ ] ...

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devtobi** [comment]
I split your request into mutiple issues under https://github.com/it-at-m/refarch-templates/issues/190 and https://github.com/it-at-m/refarch-templates/issues/189. This issue will be closed. Please make sure to split your issues into separate units where useful in the future.
On top of that, please notice we want our issues and communication to take place in english where possible, so everybody can participate evenly. Thank you!
