### ISSUE TITLE
Java Code Linting

### ISSUE THREAD

**Issue by devtobi** [it-at-m/refarch-templates#20]
**Is your feature request related to a problem? Please describe.**
Currently only Spotless is included to standardize formatting of Java-based code. However a linter should be included in the build process as well. This helps which finding code smells and bugs.

**Describe the solution you'd like**
A solution would be a tool like [PMD](https://docs.pmd-code.org/latest/index.html) or [SpotBugs](https://spotbugs.readthedocs.io/en/latest/index.html). Both are available as a Maven plugin.

When a solution is chosen, IDE Plugins should be supported as well.

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by DanielOber** [comment]
We got SonarLint, why do we need another solution?

**Comment by devtobi** [comment]
Is SonarLint integrated in the build chain? No. The usage of SonarLint depends on an external service (or an IDE plugin) and thus will not work under all circumstances. That's why I suggested to include PMD or SpotBugs that's directly integrated into the Maven build process.
Additionally, not all projects are using SonarLint responsively. That's another reason why we should enforce the use of such tools and make those available locally as well :)

**Comment by devtobi** [comment]
Yeah great, that's good. However I don't see it as a "one or the other" solution. For frontend projects we have ESLint in place. This a tool for code linting. It's embedded inside our build process. You could argue we don't need ESLint because SonarLint can do same things. Linting inside CI/CD and locally is not the same. That's why I suggest to add PMD or SpotBugs, independently of which solution we come up with for CI/CD.

**Comment by devtobi** [comment]
Follow up will be done in: https://github.com/it-at-m/refarch-templates/issues/177 due to a configuration problem.
