### ISSUE TITLE
Change Banner

### ISSUE THREAD

**Issue by DanielOber** [it-at-m/refarch-templates#22]
**Is your feature request related to a problem? Please describe.**
The current banner.txt file  still has the old name "Barracuda Archetype" in it with the old link for contribution

**Describe the solution you'd like**
Change it to "RefArch Template" and update link

**Comment by MrSebastian** [comment]
Is the update of contribution link also part of this issue: `Gib uns dein Feedback und Verbesserungsvorschläge unter https://git.muenchen.de/ccse/refarch-archetype/refarch-overview/-/issues/new?issuable_template=Feedback`

**Comment by DanielOber** [comment]
> Is the update of contribution link also part of this issue: `Gib uns dein Feedback und Verbesserungsvorschläge unter https://git.muenchen.de/ccse/refarch-archetype/refarch-overview/-/issues/new?issuable_template=Feedback`

added updating the link to the issue
