### ISSUE TITLE
[Maintenance] Renovatebot ignore some updates

### ISSUE THREAD

**Issue by devtobi** [it-at-m/refarch-templates#255]
### Problem description (optional)

Renovate bot always suggest updates to the newest available version of a dependency. However I guess we should strictly define upper boundaries to be in sync with the infrastructure and tooling we have in production in our company, and to only allow the use of LTS versions.
This means more manual updates of the allowed versions in renovatebot configuration (in consultation with the responsible persons), but a environment and tooling setup that is always going to work with the local machines and the infrastructure.

### Desired solution

The problem mentioned above applies e.g. to:
- @types/node should always have the same version of the installed Node version (LTS)
- postgres image for Docker stack should always have the same version as the latest supported in infrastructure
- keycloak image for Docker stack should always have the same version as the latest used in infrastructure
- Camel version should be manually pinned by us to only allow updates to LTS version (e.g. currently `4.4.x`)

We should include a whitelist-like behaviour for renovate bot

### Considered alternatives (optional)

===

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by simonhir** [comment]
Would also prefer that the internally used versions are enforced somehow.

**Comment by devtobi** [comment]
> Would also prefer that the internally used versions are enforced somehow. The goal should be to maintain this organisation-wide in the end.

I will create a proper renovate config in this repository for now. Later on we can try to move the renovate config to [`.github` repository](https://github.com/it-at-m/.github)
