### ISSUE TITLE
Change Logger

### ISSUE THREAD

**Issue by DanielOber** [it-at-m/refarch-templates#26]
**Is your feature request related to a problem? Please describe.**
At the moment the logger for deployment is only activated if the spring profile is dev, kon or prod. 

**Describe the solution you'd like**
Change the logger for deployments to be the default logger, without the need to add a spring profile.
Remove unnecessary loggers ("de.muenchen.allgemein is probably not needed anymore).
Introduce new profile `json-logging` to switch from normal logging format to json.

**Comment by simonhir** [comment]
@devtobi @DanielOber did you already thought about that?
We definitely should use the same profiles for the backend and the gateway.
In my opinion there are two options:
- json default and profile `local` for normal logging
- normal logging and some profile like `jsonlog` for json logging
I would rather choose the second variant but haven't come up with a meaningful json profile name yet.

**Comment by DanielOber** [comment]
we have not discussed this yet. What was the reason for the json logging? Was is because of Kibana?

**Comment by simonhir** [comment]
> What was the reason for the json logging?

Yes then you can filter and display the separate attributes.

**Comment by DanielOber** [comment]
> normal logging and some profile like jsonlog for json logging

would be my preferred solution. But maybe we wont need in the future because of the change from kibana to prometheus. For naming i would do something like `JsonLogger` or `LogToJson`

**Comment by simonhir** [comment]
> But maybe we wont need in the future because of the change from kibana to prometheus

I'm pretty sure that is not the case as you always need to parse the message and that's only really possible with json.

> For naming i would do something like JsonLogger or LogToJson

`json-logger`? As far as i know kebab-case is best practice

**Comment by simonhir** [comment]
After some discussion we renamed the profile to `json-logging`
