### ISSUE TITLE
[Bug] Stack autostarts when docker is started

### ISSUE THREAD

**Issue by DanielOber** [it-at-m/refarch-templates#309]
### Bug description

Stack starts automatically when docker is started. When you shut you restart your pc and start docker desktop, the stack is also started automatically

### Expected behaviour

After stopping docker/shutting the pc down, the stack should not automaticallystart

### Steps for reproduction

1. Shut pc down
2. start pc
3. start docker
4. stack gets started again

### Affected version

latest

### Operating system

Windows

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by simonhir** [comment]
As far as i found out there is no way than completely remove the `restart_policy`
