### ISSUE TITLE
[Feature] Streamlining Deployment to DockerHub for Commercial Adoption

### ISSUE THREAD

**Issue by ThomasAFink** [it-at-m/refarch-templates#311]
### Relevant template

refarch-frontend, refarch-backend

### Problem description (optional)

Once a Docker image is uploaded to DockerHub, deploying our reference architecture on platforms like DigitalOcean or AWS becomes relatively straightforward. To encourage broader commercial adoption and streamline both commercial and private deployments, we should consider an example workflow for uploading to DockerHub, making the process more accessible to potential users.

### Desired solution

Although Kobit-1.0.0 is somewhat outdated example, the only significant modification required for other projects is updating the JDK version in the Actions workflow.

The example below includes the relevant links to the Dockerfiles and modified forked workflows:

Frontend Dockerfile: [Kobit-Frontend Dockerfile](https://github.com/ThomasAFink/kobit-frontend/blob/dev/Dockerfile.frontend)
Backend Dockerfile: [Kobit-Backend Dockerfile](https://github.com/ThomasAFink/kobit-backend/blob/dev/Dockerfile.backend)

GitHub Workflows:
Frontend GitHub Workflow: [Link](https://github.com/ThomasAFink/kobit-frontend/blob/dev/.github/workflows/frontend.yaml#L45)
Backend GitHub Workflow: [Link](https://github.com/ThomasAFink/kobit-backend/blob/dev/.github/workflows/build.yaml#L32)

DockerHub Images:
Kobit-Frontend: [Link](https://hub.docker.com/r/thomasafink/kobit-frontend)
Kobit-Backend: [Link](https://hub.docker.com/r/thomasafink/kobit-backend)

![screenshot](https://github.com/user-attachments/assets/d3b82aea-09c2-4d7e-864f-25deea9ae473)

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devtobi** [comment]
I am curious to why DockerHub is required in order for DigitalOcean or AWS to be able to use the images. Your screenshot above shows "GitHub Container Registry" underneath so I guess a deployment to Dockerhub is not necessary. Currently we chose GitHub as our image registry and changing this has more people involved.
