### ISSUE TITLE
Combine gitignore files

### ISSUE THREAD

**Issue by DanielOber** [it-at-m/refarch-templates#36]
**Is your feature request related to a problem? Please describe.**
There are separate gitignore files in every template. To enforce monorepo usage this file should be placed at root using only 1 gitignore file. 

**Describe the solution you'd like**
Single gitignore file with merged content.

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by devtobi** [comment]
Maybe it would be even better to have 1 central .gitignore file for the whole repository?

**Comment by DanielOber** [comment]
> Maybe it would be even better to have 1 central .gitignore file for the whole repository?

i dont think so. because maybe you just need a frontend or just need a backend. So each template should have its one .gitignore file

**Comment by devtobi** [comment]
I think we should wait with this topic until we have the "webcomponent" template in place as well. Then we can combine all 4 .gitignore files into one and store it in repository root.
