### ISSUE TITLE
[Bug] JsonLogginConfigurationTests not running correctly

### ISSUE THREAD

**Issue by hupling** [it-at-m/refarch-templates#362]
### Bug description

siehe https://github.com/it-at-m/refarch-templates/pull/279#issuecomment-2377020168

### Expected behaviour

test sind grün

### Steps for reproduction

siehe pipeline durchlauf

### Affected version

akutelle

### Affected template

refarch-backend, refarch-eai

### Last working version (optional)

aktuelle

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devtobi** [comment]
I debugged the issue and found out that:
- @DirtiesContext for the JsonLoggingConfiguration class starts a fresh Spring context with the correct "json-logging" profile
- The logback configuration itself dos not change and which ever configuration is used first is used throughout the whole test suite (I debugged this by adding `<statusListener class="ch.qos.logback.core.status.OnConsoleStatusListener" />` to the logback configuration file
- I tried different versions of @DirtiesContext (e.g. BEFORE_CLASS), when using `BEFORE_EACH_TEST_METHOD` tests work but the wrong json-logging is also used for follow up test classes
- I tried the solution mentioned in https://stackoverflow.com/a/39292587
