### ISSUE TITLE
[Maintenance] Add linting of markdown files to vitepress documentation

### ISSUE THREAD

**Issue by devtobi** [it-at-m/refarch-templates#428]
### Problem description (optional)

We write our Vitepress documentation using markdown files.
We should add tooling to verify the correct formatting and syntax of those markdown files.

### Desired solution

The only tool I found (which is actively maintained) is https://github.com/DavidAnson/markdownlint. It is highly customizable and can be run as a standalone npm tool (so adding as devDependency and creating a lint job would be sufficient).
Alternatively it can also be integrated into ESLint (if we decide to later on include it because we need custom code for our documentation)
Remove code linting for HTML in Prettier as Prettier should only care about formatting.

### Considered alternatives (optional)

Only use already available tooling like Prettier.

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devtobi** [comment]
I'd highly encourage to add this before we start writing real documentation. @DanielOber what do you think about this?

**Comment by devtobi** [comment]
@DanielOber just another reminder for you. ;)

**Comment by DanielOber** [comment]
@devtobi sorry, complelty missed that one. I'm not sure if we really need it. Most ideas or even text editors already support markdown. Having a specially configured tool for it seems unnecessarily complicated to me, but I haven't tried it yet. If we keep it simple, we could give it a try.

**Comment by devtobi** [comment]
> @devtobi sorry, complelty missed that one. I'm not sure if we really need it. Most ideas or even text editors already support markdown. Having a specially configured tool for it seems unnecessarily complicated to me, but I haven't tried it yet. If we keep it simple, we could give it a try.

I think we shouldn't rely on the features of IDEs and text editors as those differ drastly from each other and does not prevent the release of bad markdown when edited e.g. via online GUI. Thats why I suggest to include this tool (without any specific configuration) inside the lint step for documentation. Its just another safety net I'd like to include.
