### ISSUE TITLE
API-Gateway - Bump dependency versions

### ISSUE THREAD

**Issue by devtobi** [it-at-m/refarch-templates#52]
**Is your feature request related to a problem? Please describe.**
Version dependencies should be bumped to the latest LTS versions (if available).
Major or minor changes might deprecated certain APIs or configuration properties and thus a refactoring might be needed.

**Describe the solution you'd like**
All dependency versions in `pom.xml` are bumped to the latest versions

**Describe alternatives you've considered**
---

**Additional context**
----

**Comment by simonhir** [comment]
Already done within https://github.com/it-at-m/refarch and Renovate
