### ISSUE TITLE
[Feature] make database h2 avaiable 

### ISSUE THREAD

**Issue by hupling** [it-at-m/refarch-templates#538]
### Relevant template

refarch-backend

### Desired solution

in the moment only postgress is working

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DanielOber** [comment]
@hupling That's why the stack includes a PostgresDB. Your local environment should always use the same technology that you use in your development, testing, and production environments.

**Comment by hupling** [comment]
@MrSebastian hat gesagt, dass ihr dann zwei Dialekte pflegen müsst. Also h2 und postgress. Das war mir nicht so bewusst, ich habe gedacht jdbc macht alles. Er meinte auch, dass man irgendwie eine Postgress auch als Service irgendwie starten kann. Leider habt ihr noch überhaupt keine  Doku daher weiß ich nicht, welche Funktionen ihr anbietet und wie ich die aktivere.  

Also für unsere Test Github Pipelines brauchen wir dann auch eine Postgress DB. Das war mir nicht so bewusst.


Ich finde es toll, wenn man zumindest beides anbietet. Dann kann der Nutzer entscheiden, was er will.
