### ISSUE TITLE
[Feature] Setup database migration (i.e. Flyway)

### ISSUE THREAD

**Issue by simonhir** [it-at-m/refarch-templates#543]
### Relevant template

refarch-backend

### Desired solution

Instead of hibernate ddl-auto a real db migration tool should be added for reproducible behavior.
Also this enforces database changes are only made explicitly by providing specific migrations.

The decision on which tool to use should also be made in this issue (i.e. flyway).

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eidottermihi** [comment]
:+1: for using Flyway for database migrations:

- already used internally in lots of projects (https://git.muenchen.de/search?scope=blobs&search=org.flywaydb+filename%3Apom.xml - 72 hits - Liquibase: https://git.muenchen.de/search?scope=blobs&search=org.liquibase+filename%3Apom.xml - 7 hits) 
- good Spring Boot / Maven integration
- features of Community Edition are sufficient (IMO)

Disclaimer: I never used Liquibase ;)

If the decision is Flyway, I'm happy to make the code contribution

**Comment by DanielOber** [comment]
@eidottermihi 

I discussed this with @devtobi, and we've decided to use Flyway for database migrations. If you're interested and have the time, feel free to assign the ticket to yourself and contribute. 👍
