### ISSUE TITLE
[Bug] stack: appswitcher-server healtcheck not working 

### ISSUE THREAD

**Issue by eidottermihi** [it-at-m/refarch-templates#634]
### Bug description

The current healthcheck uses curl to query the actuator endpoint, but the image of appswitcher-server does not include curl

$ curl http://localhost:8080/actuator/health/liveness
/bin/sh: 1: curl: not found

-> container is reported as "unhealthy"

### Expected behaviour

It should be healthy

### Steps for reproduction

run curl http://localhost:8080/actuator/health/liveness

### Affected version

main

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devtobi** [comment]
Wouldn't it be better if the health check logic is embedded in the image itself instead of providing it in the docker compose file manually?
Dockerfile has the HEALTHCHECK keyword for that.
