### ISSUE TITLE
Change Start page Text

### ISSUE THREAD

**Issue by DanielOber** [it-at-m/refarch-templates#68]
**Is your feature request related to a problem? Please describe.**
At the start page, the text says "Refarch-kick Starter", but we will have other frontend templates as well. It would be better to change the text to make it clear what it is. 

**Describe the solution you'd like**
Change the text to something better e.g. RefArchFrontendTemplate

**Comment by DanielOber** [comment]
@devtobi The Text already changed to `Willkommen beim refarch-frontend von it@M `. That would be fine for me, so we can close that issue. Or do you think it should be changed to something else?

**Comment by devtobi** [comment]
This is fine for me. Issue can be closed.
