### ISSUE TITLE
Should unit componenttesting still be supported

### ISSUE THREAD

**Issue by DanielOber** [it-at-m/refarch-templates#77]
**Is your feature request related to a problem? Please describe.**
https://github.com/it-at-m/refarch-templates/pull/61#discussion_r1687699107

"Are we going to support component testing in the future? There was not that much consent for unit testing Vue components in the past. We should discuss if we want to further include this."

**Comment by devtobi** [comment]
Closed because of https://github.com/it-at-m/refarch-templates/discussions/127
