### ISSUE TITLE
Security: verify Token Audience

### ISSUE THREAD

**Issue by DanielOber** [it-at-m/refarch-templates#91]
**Is your feature request related to a problem? Please describe.**
At the moment, there is no verification for the Token Audience in the backend

**Describe the solution you'd like**
[Verify Token Audience](https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/jwt.html#oauth2resourceserver-jwt-validation-custom)

**Comment by eidottermihi** [comment]
done with #133
